name: Mein erster Workflow

on: push

jobs:
  sag-hallo:
    runs-on: ubuntu-latest
    steps:
      - name: Sag hallo
        run: echo "Hallo von GitHub Actions! 🚀"

      - name: Was läuft hier?
        run: |
          echo "Ich laufe auf:"
          uname -a
          echo "Mit User:"
          whoami
          echo "Datum:"
          date

      - name: Lieblingsessen
        run:
          echo "Mein Lieblingsessen  ist Pizza"

      - name: README.md ausgeben
        run:
          cat READ.md
